---
strategy: webhook
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: ''
id: 187257
custom_fields:
- keyname: webhook_url
  name: Plugin ID / Webhook URL
  field_type: string
  description: The <b>Plugin ID</b> or the <b>Webhook URL</b> of this plugin instance.
  required: true
  placeholder: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  help_text: Find this in your plugin settings or copy just the UUID portion
- keyname: expiry_hours
  field_type: number
  name: Message Expiry (hours)
  placeholder: '24'
  default: 24
  min: 1
  max: 8760
  help_text: Messages older than this will be cleared (e.g., 1, 6, 24, 168 for one week)
- keyname: show_advanced
  field_type: select
  name: Show Advanced Options
  options:
  - 'No'
  - 'Yes'
  default: 'no'
  help_text: Show additional customization options
  conditional_validation:
  - when: 'no'
    hidden:
    - custom_scan_message
    - show_qr_code
    - show_second_message
    - author_required
    - message_required
    - skip_if_older_than
- keyname: custom_scan_message
  field_type: text
  name: Custom Scan Message
  description: Text shown next to the QR code
  placeholder: |-
    **SCAN** TO

    LEAVE A

    **MESSAGE**
  help_text: Supports Markdown. Use \n for line breaks.
  default: |-
    **SCAN** TO

    LEAVE A

    **MESSAGE**
  optional: true
- keyname: show_qr_code
  field_type: select
  name: Show QR Code
  options:
  - Show
  - Hide
  default: show
  help_text: Display or hide the QR code in the bottom-right corner
  optional: true
- keyname: show_second_message
  field_type: select
  name: Show Previous Message
  options:
  - Show
  - Hide
  default: show
  help_text: Display the second most recent message in the bottom-left corner
  optional: true
- keyname: author_required
  field_type: select
  name: Author Field Requirement
  options:
  - Optional
  - Required
  default: optional
  help_text: Make the author name field mandatory in the submission form
  optional: true
- keyname: message_required
  field_type: select
  name: Message Field Requirement
  options:
  - Optional (if image provided): optional
  - Required: required
  default: optional
  help_text: Make the message text field mandatory in the submission form
  optional: true
- keyname: skip_if_older_than
  field_type: number
  name: Skip Display if No Recent Messages (hours)
  placeholder: '0'
  default: 0
  min: 0
  max: 8760
  help_text: Skip this screen in the playlist if the most recent message is older than X hours. Set to 0 to disable (never skip).
  optional: true
name: Leave a message
refresh_interval: 5
